// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/sched.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedService_SubmitIntent_FullMethodName = "/sched.SchedService/SubmitIntent"
	SchedService_GetTask_FullMethodName      = "/sched.SchedService/GetTask"
)

// SchedServiceClient is the client API for SchedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RPC Service Definition
type SchedServiceClient interface {
	SubmitIntent(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type schedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedServiceClient(cc grpc.ClientConnInterface) SchedServiceClient {
	return &schedServiceClient{cc}
}

func (c *schedServiceClient) SubmitIntent(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, SchedService_SubmitIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedServiceClient) GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, SchedService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedServiceServer is the server API for SchedService service.
// All implementations must embed UnimplementedSchedServiceServer
// for forward compatibility.
//
// RPC Service Definition
type SchedServiceServer interface {
	SubmitIntent(context.Context, *SubmitRequest) (*SubmitResponse, error)
	GetTask(context.Context, *TaskRequest) (*TaskResponse, error)
	mustEmbedUnimplementedSchedServiceServer()
}

// UnimplementedSchedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedServiceServer struct{}

func (UnimplementedSchedServiceServer) SubmitIntent(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitIntent not implemented")
}
func (UnimplementedSchedServiceServer) GetTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedSchedServiceServer) mustEmbedUnimplementedSchedServiceServer() {}
func (UnimplementedSchedServiceServer) testEmbeddedByValue()                      {}

// UnsafeSchedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedServiceServer will
// result in compilation errors.
type UnsafeSchedServiceServer interface {
	mustEmbedUnimplementedSchedServiceServer()
}

func RegisterSchedServiceServer(s grpc.ServiceRegistrar, srv SchedServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedService_ServiceDesc, srv)
}

func _SchedService_SubmitIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedServiceServer).SubmitIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedService_SubmitIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedServiceServer).SubmitIntent(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedServiceServer).GetTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedService_ServiceDesc is the grpc.ServiceDesc for SchedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sched.SchedService",
	HandlerType: (*SchedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitIntent",
			Handler:    _SchedService_SubmitIntent_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _SchedService_GetTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sched.proto",
}
