// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sched.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GovernanceMode int32

const (
	GovernanceMode_ADVISORY_ONLY GovernanceMode = 0
	GovernanceMode_AUTONOMOUS    GovernanceMode = 1
	GovernanceMode_HUMAN_GATE    GovernanceMode = 2
)

// Enum value maps for GovernanceMode.
var (
	GovernanceMode_name = map[int32]string{
		0: "ADVISORY_ONLY",
		1: "AUTONOMOUS",
		2: "HUMAN_GATE",
	}
	GovernanceMode_value = map[string]int32{
		"ADVISORY_ONLY": 0,
		"AUTONOMOUS":    1,
		"HUMAN_GATE":    2,
	}
)

func (x GovernanceMode) Enum() *GovernanceMode {
	p := new(GovernanceMode)
	*p = x
	return p
}

func (x GovernanceMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GovernanceMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sched_proto_enumTypes[0].Descriptor()
}

func (GovernanceMode) Type() protoreflect.EnumType {
	return &file_proto_sched_proto_enumTypes[0]
}

func (x GovernanceMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GovernanceMode.Descriptor instead.
func (GovernanceMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{0}
}

type TaskState int32

const (
	TaskState_CREATED               TaskState = 0
	TaskState_PENDING               TaskState = 1
	TaskState_RUNNING               TaskState = 2
	TaskState_COMPLETED             TaskState = 3
	TaskState_FAILED                TaskState = 4
	TaskState_ANALYZING             TaskState = 5
	TaskState_NEEDS_APPROVAL        TaskState = 6
	TaskState_AWAITING_PREREQUISITE TaskState = 7 // <--- ADDED: Waiting for dependency
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "CREATED",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
		5: "ANALYZING",
		6: "NEEDS_APPROVAL",
		7: "AWAITING_PREREQUISITE",
	}
	TaskState_value = map[string]int32{
		"CREATED":               0,
		"PENDING":               1,
		"RUNNING":               2,
		"COMPLETED":             3,
		"FAILED":                4,
		"ANALYZING":             5,
		"NEEDS_APPROVAL":        6,
		"AWAITING_PREREQUISITE": 7,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sched_proto_enumTypes[1].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_proto_sched_proto_enumTypes[1]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{1}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IntentYaml    string                 `protobuf:"bytes,2,opt,name=intent_yaml,json=intentYaml,proto3" json:"intent_yaml,omitempty"`
	State         TaskState              `protobuf:"varint,3,opt,name=state,proto3,enum=sched.TaskState" json:"state,omitempty"`
	Logs          []string               `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	Mode          GovernanceMode         `protobuf:"varint,5,opt,name=mode,proto3,enum=sched.GovernanceMode" json:"mode,omitempty"`
	IsSimulation  bool                   `protobuf:"varint,6,opt,name=is_simulation,json=isSimulation,proto3" json:"is_simulation,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	AiInsight     string                 `protobuf:"bytes,8,opt,name=ai_insight,json=aiInsight,proto3" json:"ai_insight,omitempty"`
	PreRunScript  string                 `protobuf:"bytes,9,opt,name=pre_run_script,json=preRunScript,proto3" json:"pre_run_script,omitempty"`     // Add this
	PostRunScript string                 `protobuf:"bytes,10,opt,name=post_run_script,json=postRunScript,proto3" json:"post_run_script,omitempty"` // Add this
	DependsOn     string                 `protobuf:"bytes,11,opt,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`               // <--- ADDED: Parent Task ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_sched_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetIntentYaml() string {
	if x != nil {
		return x.IntentYaml
	}
	return ""
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_CREATED
}

func (x *Task) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Task) GetMode() GovernanceMode {
	if x != nil {
		return x.Mode
	}
	return GovernanceMode_ADVISORY_ONLY
}

func (x *Task) GetIsSimulation() bool {
	if x != nil {
		return x.IsSimulation
	}
	return false
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetAiInsight() string {
	if x != nil {
		return x.AiInsight
	}
	return ""
}

func (x *Task) GetPreRunScript() string {
	if x != nil {
		return x.PreRunScript
	}
	return ""
}

func (x *Task) GetPostRunScript() string {
	if x != nil {
		return x.PostRunScript
	}
	return ""
}

func (x *Task) GetDependsOn() string {
	if x != nil {
		return x.DependsOn
	}
	return ""
}

type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_proto_sched_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{1}
}

func (x *ApproveRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_proto_sched_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApproveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_proto_sched_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_proto_sched_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YamlContent   string                 `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"` // <--- Add this
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_proto_sched_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitRequest) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

func (x *SubmitRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_sched_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_sched_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{7}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_sched_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_sched_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{9}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_sched_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sched_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_sched_proto_rawDescGZIP(), []int{10}
}

func (x *JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sched_proto protoreflect.FileDescriptor

const file_proto_sched_proto_rawDesc = "" +
	"\n" +
	"\x11proto/sched.proto\x12\x05sched\"\xf0\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vintent_yaml\x18\x02 \x01(\tR\n" +
	"intentYaml\x12&\n" +
	"\x05state\x18\x03 \x01(\x0e2\x10.sched.TaskStateR\x05state\x12\x12\n" +
	"\x04logs\x18\x04 \x03(\tR\x04logs\x12)\n" +
	"\x04mode\x18\x05 \x01(\x0e2\x15.sched.GovernanceModeR\x04mode\x12#\n" +
	"\ris_simulation\x18\x06 \x01(\bR\fisSimulation\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"ai_insight\x18\b \x01(\tR\taiInsight\x12$\n" +
	"\x0epre_run_script\x18\t \x01(\tR\fpreRunScript\x12&\n" +
	"\x0fpost_run_script\x18\n" +
	" \x01(\tR\rpostRunScript\x12\x1d\n" +
	"\n" +
	"depends_on\x18\v \x01(\tR\tdependsOn\")\n" +
	"\x0eApproveRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"E\n" +
	"\x0fApproveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x0fRollbackRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"F\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\rSubmitRequest\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\tR\vyamlContent\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\")\n" +
	"\x0eSubmitResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"&\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"/\n" +
	"\fTaskResponse\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.sched.TaskR\x04task\"@\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"B\n" +
	"\fJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*C\n" +
	"\x0eGovernanceMode\x12\x11\n" +
	"\rADVISORY_ONLY\x10\x00\x12\x0e\n" +
	"\n" +
	"AUTONOMOUS\x10\x01\x12\x0e\n" +
	"\n" +
	"HUMAN_GATE\x10\x02*\x8b\x01\n" +
	"\tTaskState\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tANALYZING\x10\x05\x12\x12\n" +
	"\x0eNEEDS_APPROVAL\x10\x06\x12\x19\n" +
	"\x15AWAITING_PREREQUISITE\x10\a2\xb6\x02\n" +
	"\fSchedService\x12;\n" +
	"\fSubmitIntent\x12\x14.sched.SubmitRequest\x1a\x15.sched.SubmitResponse\x122\n" +
	"\aGetTask\x12\x12.sched.TaskRequest\x1a\x13.sched.TaskResponse\x12<\n" +
	"\vApproveTask\x12\x15.sched.ApproveRequest\x1a\x16.sched.ApproveResponse\x12?\n" +
	"\fRollbackTask\x12\x16.sched.RollbackRequest\x1a\x17.sched.RollbackResponse\x126\n" +
	"\vJoinCluster\x12\x12.sched.JoinRequest\x1a\x13.sched.JoinResponseB+Z)github.com/venusai24/task-scheduler/protob\x06proto3"

var (
	file_proto_sched_proto_rawDescOnce sync.Once
	file_proto_sched_proto_rawDescData []byte
)

func file_proto_sched_proto_rawDescGZIP() []byte {
	file_proto_sched_proto_rawDescOnce.Do(func() {
		file_proto_sched_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sched_proto_rawDesc), len(file_proto_sched_proto_rawDesc)))
	})
	return file_proto_sched_proto_rawDescData
}

var file_proto_sched_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_sched_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_sched_proto_goTypes = []any{
	(GovernanceMode)(0),      // 0: sched.GovernanceMode
	(TaskState)(0),           // 1: sched.TaskState
	(*Task)(nil),             // 2: sched.Task
	(*ApproveRequest)(nil),   // 3: sched.ApproveRequest
	(*ApproveResponse)(nil),  // 4: sched.ApproveResponse
	(*RollbackRequest)(nil),  // 5: sched.RollbackRequest
	(*RollbackResponse)(nil), // 6: sched.RollbackResponse
	(*SubmitRequest)(nil),    // 7: sched.SubmitRequest
	(*SubmitResponse)(nil),   // 8: sched.SubmitResponse
	(*TaskRequest)(nil),      // 9: sched.TaskRequest
	(*TaskResponse)(nil),     // 10: sched.TaskResponse
	(*JoinRequest)(nil),      // 11: sched.JoinRequest
	(*JoinResponse)(nil),     // 12: sched.JoinResponse
}
var file_proto_sched_proto_depIdxs = []int32{
	1,  // 0: sched.Task.state:type_name -> sched.TaskState
	0,  // 1: sched.Task.mode:type_name -> sched.GovernanceMode
	2,  // 2: sched.TaskResponse.task:type_name -> sched.Task
	7,  // 3: sched.SchedService.SubmitIntent:input_type -> sched.SubmitRequest
	9,  // 4: sched.SchedService.GetTask:input_type -> sched.TaskRequest
	3,  // 5: sched.SchedService.ApproveTask:input_type -> sched.ApproveRequest
	5,  // 6: sched.SchedService.RollbackTask:input_type -> sched.RollbackRequest
	11, // 7: sched.SchedService.JoinCluster:input_type -> sched.JoinRequest
	8,  // 8: sched.SchedService.SubmitIntent:output_type -> sched.SubmitResponse
	10, // 9: sched.SchedService.GetTask:output_type -> sched.TaskResponse
	4,  // 10: sched.SchedService.ApproveTask:output_type -> sched.ApproveResponse
	6,  // 11: sched.SchedService.RollbackTask:output_type -> sched.RollbackResponse
	12, // 12: sched.SchedService.JoinCluster:output_type -> sched.JoinResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sched_proto_init() }
func file_proto_sched_proto_init() {
	if File_proto_sched_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sched_proto_rawDesc), len(file_proto_sched_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sched_proto_goTypes,
		DependencyIndexes: file_proto_sched_proto_depIdxs,
		EnumInfos:         file_proto_sched_proto_enumTypes,
		MessageInfos:      file_proto_sched_proto_msgTypes,
	}.Build()
	File_proto_sched_proto = out.File
	file_proto_sched_proto_goTypes = nil
	file_proto_sched_proto_depIdxs = nil
}
